<?php


namespace webServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PruebaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpleadosGraRepository extends EntityRepository
{
}
